trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'
  SolutionName: CG.Validations
  SolutionPath: 'src/$(SolutionName)'

steps:

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.1.0'
    checkLatest: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    nugetConfigPath: 'nuget.config'
    feedsToUse: config
    arguments: '--interactive'
    projects: '$(SolutionPath).sln'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'
    projects: '$(SolutionPath).sln'
    
- task: DotNetCoreCLI@2
  displayName: "dotnet test"
  inputs:
    command: 'test'
    projects: '$(SolutionPath).sln'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    publishTestResults: true
    nobuild: true

- task: PublishCodeCoverageResults@1
  displayName: "publish coverage"
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'src/**/coverage.cobertura.xml'
    pathToSources: '$(SolutionPath)'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(BuildConfiguration)'    
    packagesToPack: '$(SolutionPath).sln'
    nobuild: true
    versioningScheme: 'off'    
  
- task: NuGetCommand@2
  displayName: 'nuget internal push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'codegator'
    versioningScheme: 'off'
    allowPackageConflicts: true    
        
- task: NuGetCommand@2
  displayName: 'nuget external push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NUGET.ORG'
    versioningScheme: 'off'
    allowPackageConflicts: true 
    arguments: -SkipDuplicate  

